//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asa.Media.Controls.Properties
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asa.Media.Controls.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap AddProduct
		{
			get
			{
				object obj = ResourceManager.GetObject("AddProduct", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap AddProgram
		{
			get
			{
				object obj = ResourceManager.GetObject("AddProgram", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap CalendarDisabled
		{
			get
			{
				object obj = ResourceManager.GetObject("CalendarDisabled", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap CalendarOptionsDataSource
		{
			get
			{
				object obj = ResourceManager.GetObject("CalendarOptionsDataSource", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap CloneProduct
		{
			get
			{
				object obj = ResourceManager.GetObject("CloneProduct", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap DeleteButton
		{
			get
			{
				object obj = ResourceManager.GetObject("DeleteButton", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap DeleteProduct
		{
			get
			{
				object obj = ResourceManager.GetObject("DeleteProduct", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap DeleteProgram
		{
			get
			{
				object obj = ResourceManager.GetObject("DeleteProgram", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap DeleteSchedule
		{
			get
			{
				object obj = ResourceManager.GetObject("DeleteSchedule", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap EmailBig
		{
			get
			{
				object obj = ResourceManager.GetObject("EmailBig", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Exit
		{
			get
			{
				object obj = ResourceManager.GetObject("Exit", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Favorites
		{
			get
			{
				object obj = ResourceManager.GetObject("Favorites", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap FavoritesLogo
		{
			get
			{
				object obj = ResourceManager.GetObject("FavoritesLogo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Floater
		{
			get
			{
				object obj = ResourceManager.GetObject("Floater", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Help
		{
			get
			{
				object obj = ResourceManager.GetObject("Help", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap HelpSmall
		{
			get
			{
				object obj = ResourceManager.GetObject("HelpSmall", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap HomeCalendar
		{
			get
			{
				object obj = ResourceManager.GetObject("HomeCalendar", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap HomeConceptTitleLogo
		{
			get
			{
				object obj = ResourceManager.GetObject("HomeConceptTitleLogo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap HomeDefaultLogo
		{
			get
			{
				object obj = ResourceManager.GetObject("HomeDefaultLogo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap HomeLogo
		{
			get
			{
				object obj = ResourceManager.GetObject("HomeLogo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap HomeOptions
		{
			get
			{
				object obj = ResourceManager.GetObject("HomeOptions", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap HomeScheduleTitleLogo
		{
			get
			{
				object obj = ResourceManager.GetObject("HomeScheduleTitleLogo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap HomeSnapshot
		{
			get
			{
				object obj = ResourceManager.GetObject("HomeSnapshot", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap MonthlySchedule
		{
			get
			{
				object obj = ResourceManager.GetObject("MonthlySchedule", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap NewScheduleRibbon
		{
			get
			{
				object obj = ResourceManager.GetObject("NewScheduleRibbon", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap NudgeDown
		{
			get
			{
				object obj = ResourceManager.GetObject("NudgeDown", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap NudgeUp
		{
			get
			{
				object obj = ResourceManager.GetObject("NudgeUp", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap OpenSchedule
		{
			get
			{
				object obj = ResourceManager.GetObject("OpenSchedule", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap OpenScheduleRibbon
		{
			get
			{
				object obj = ResourceManager.GetObject("OpenScheduleRibbon", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap OptionsNew
		{
			get
			{
				object obj = ResourceManager.GetObject("OptionsNew", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap OptionsNoPrograms
		{
			get
			{
				object obj = ResourceManager.GetObject("OptionsNoPrograms", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap OptionsNoRecords
		{
			get
			{
				object obj = ResourceManager.GetObject("OptionsNoRecords", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Pdf
		{
			get
			{
				object obj = ResourceManager.GetObject("Pdf", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap PowerPoint
		{
			get
			{
				object obj = ResourceManager.GetObject("PowerPoint", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Preview
		{
			get
			{
				object obj = ResourceManager.GetObject("Preview", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Quarter
		{
			get
			{
				object obj = ResourceManager.GetObject("Quarter", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap RibbonLogo
		{
			get
			{
				object obj = ResourceManager.GetObject("RibbonLogo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap SaveAs
		{
			get
			{
				object obj = ResourceManager.GetObject("SaveAs", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap SaveSmall
		{
			get
			{
				object obj = ResourceManager.GetObject("SaveSmall", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap SectionNew
		{
			get
			{
				object obj = ResourceManager.GetObject("SectionNew", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap SectionNoPrograms
		{
			get
			{
				object obj = ResourceManager.GetObject("SectionNoPrograms", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap SectionNoRecords
		{
			get
			{
				object obj = ResourceManager.GetObject("SectionNoRecords", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap SectionSettingsDigital
		{
			get
			{
				object obj = ResourceManager.GetObject("SectionSettingsDigital", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap SectionSettingsInfo
		{
			get
			{
				object obj = ResourceManager.GetObject("SectionSettingsInfo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap SectionSettingsOptions
		{
			get
			{
				object obj = ResourceManager.GetObject("SectionSettingsOptions", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap SectionSettingsRadio
		{
			get
			{
				object obj = ResourceManager.GetObject("SectionSettingsRadio", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap SectionSettingsTV
		{
			get
			{
				object obj = ResourceManager.GetObject("SectionSettingsTV", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap SnapshotNew
		{
			get
			{
				object obj = ResourceManager.GetObject("SnapshotNew", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap SnapshotNoRecords
		{
			get
			{
				object obj = ResourceManager.GetObject("SnapshotNoRecords", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap SnapshotSettingsActiveWeeks
		{
			get
			{
				object obj = ResourceManager.GetObject("SnapshotSettingsActiveWeeks", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap SnapshotsNoPrograms
		{
			get
			{
				object obj = ResourceManager.GetObject("SnapshotsNoPrograms", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap SummaryOptionsFavorites
		{
			get
			{
				object obj = ResourceManager.GetObject("SummaryOptionsFavorites", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap SummaryOptionsInfo
		{
			get
			{
				object obj = ResourceManager.GetObject("SummaryOptionsInfo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap SummaryOptionsType
		{
			get
			{
				object obj = ResourceManager.GetObject("SummaryOptionsType", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap WeeklySchedule
		{
			get
			{
				object obj = ResourceManager.GetObject("WeeklySchedule", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
